name: eti_chat
description: "chat buddy"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1


  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  get_it: ^7.6.7
  firebase_messaging: ^14.1.1
  firebase_core: ^2.3.0
  flutter_local_notifications: ^17.2.1+2
  flutter_secure_storage: ^9.2.2
  dio: ^5.5.0+1
  change_app_package_name: ^1.3.0
#  qr_mobile_vision:
#    git:
#      url: https://github.com/4gmayank/flutter_qr_mobile_vision.git
#      ref: 590572ee
  qr_mobile_vision: ^5.0.1
  animated_snack_bar: ^0.4.0
  qr_flutter: ^4.1.0
  dev: ^1.0.0
  pinput: ^5.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9

flutter:

  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/images/
    - assets/fonts/
